image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "27"
  ANDROID_BUILD_TOOLS: "27.0.2"
  ANDROID_SDK_TOOLS: "25.2.5"

before_script:
  - echo ${ANDROID_SDK_TOOLS}
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip "https://dl.google.com/android/repository/tools_r${ANDROID_SDK_TOOLS}-linux.zip"
  - unzip android-sdk.zip -d android-sdk
  - echo y | android-sdk/tools/android --silent update sdk --no-ui --all --filter "android-${ANDROID_COMPILE_SDK}",platform-tools,"build-tools-${ANDROID_BUILD_TOOLS}",extra-android-m2repository,extra-google-google_play_services,extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk
  - export PATH=$PATH:$PWD/android-sdk/platform-tools/
  - chmod +x ./gradlew

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew --no-daemon assemble
    - ./gradlew --no-daemon install
  artifacts:
    paths:
      - build/outputs/
      - build/libs/
      - build/poms/

#unitTests:
#  stage: test
#  script:
#    - ./gradlew --no-daemon test

#functionalTests:
#  stage: test
#  script:
#    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
#    - chmod +x android-wait-for-emulator
#    - echo y | android-sdk/tools/android --silent update sdk --no-ui --all --filter sys-img-x86-google_apis-${ANDROID_COMPILE_SDK}
#    - echo no | android-sdk/tools/android create avd -n test -t android-${ANDROID_COMPILE_SDK} --abi google_apis/x86
#    - android-sdk/tools/emulator64-x86 -avd test -no-window -no-audio &
#    - ./android-wait-for-emulator
#    - adb shell input keyevent 82
#    - ./gradlew --no-daemon cAT
#  artifacts:
#    paths:
#    - app/build/reports/androidTests/
